### ISSUE TITLE
Holhographic sign dont work 1.12.2-0.7.2-universal.jar

### ISSUE THREAD

**Issue by Njet75** [infiniteblock/MatterOverdrive-Community-Edition#1]
Holhographic sign don´t work 1.12.2-0.7.2-universal.jar
Its missing texture

**Comment by infiniteblock** [comment]
![image](https://user-images.githubusercontent.com/5800555/146684504-2fa4f3fb-b066-4259-a066-cc64f705cc9b.png)
Can you be more specific?

**Comment by Njet75** [comment]
![2021-12-19_22 19 11](https://user-images.githubusercontent.com/8996171/146691188-4e38c149-23b1-4f1c-a0b7-f1548394f4fd.png)

Strange .I have no texture nor function.
It might be my texturepack?
/ Michael

**Comment by infiniteblock** [comment]
could you send more details of the modpack and texture pack also not sure why its called matteroverdrive:holo_sign#inventory as it should be matteroverdrive:holo_sign

**Comment by Njet75** [comment]
I have narrowed it down to Hbm's Nuclear Tech Mod Reloaded   version hbm-1.6.4a-Gv1
When unistalled it works perfect.With both mods it dont work.
