### ISSUE TITLE
Android Icons half white icons

### ISSUE THREAD

**Issue by Gandalf360one** [infiniteblock/MatterOverdrive-Community-Edition#10]
In the current version they are not white because the textures dont have the transition from transparent to white.

The textures have to be switched witth one from an older verion.
Here is an example how they look and how they should look like:
1.7.10 (how they should be)
![MO1 7 10](https://user-images.githubusercontent.com/48660271/151649687-983e5dae-a96e-4eab-bf5f-307ab7e05d46.JPG)

1.12.2
![MO1 12 2](https://user-images.githubusercontent.com/48660271/151649698-4668e06b-cf7c-4213-abb7-afad6e1ba9f2.JPG)

**Comment by infiniteblock** [comment]
Fixed in 0.7.5
