### ISSUE TITLE
Android pills are completly collored instead of only the half

### ISSUE THREAD

**Issue by Gandalf360one** [infiniteblock/MatterOverdrive-Community-Edition#11]
The whole android pill is one color instead of half colored and half white.

1.7.10
![MO_pills1 7 10](https://user-images.githubusercontent.com/48660271/151649821-24475272-c055-4f03-9eae-0f5a4d998e60.JPG)

1.12.2
![MO_pills1 12 2](https://user-images.githubusercontent.com/48660271/151649856-c3a70787-515e-4d0e-a865-9b2445db312a.JPG)

**Comment by infiniteblock** [comment]
Fixed in 0.7.5
