### ISSUE TITLE
[BUG] Server crashes when using ThaumCraft 6's world salt

### ISSUE THREAD

**Issue by KasumiNova** [infiniteblock/MatterOverdrive-Community-Edition#16]
Crash report
https://paste.ubuntu.com/p/bJqq3frsyy/

**Comment by infiniteblock** [comment]
what do you mean? world salt? ive never used thaumcraft if u can explain how i can reproduce i can look into it

**Comment by infiniteblock** [comment]
no info no fix.

**Comment by infiniteblock** [comment]
Should be same as #42 so is now fixed.
