### ISSUE TITLE
0.7.6b Bug

### ISSUE THREAD

**Issue by newfengye** [infiniteblock/MatterOverdrive-Community-Edition#17]
"Item Magnet"and"High Jump"invalid

**Comment by infiniteblock** [comment]
Give more details ..

**Comment by newfengye** [comment]
Android skill items are not absorbed

Can't jump higher

**Comment by infiniteblock** [comment]
High jump is fixed, magnet needs more work

**Comment by newfengye** [comment]
Android skill "Plasma Shield" and "Emergency Shields" invalid
