### ISSUE TITLE
Android skill "Plasma Shield" and "Emergency Shields" invalid

### ISSUE THREAD

**Issue by newfengye** [infiniteblock/MatterOverdrive-Community-Edition#18]
Android skill "Plasma Shield" and "Emergency Shields" invalid

0.7.7 bug

_Originally posted by @newfengye in https://github.com/infiniteblock/MatterOverdrive-Community-Edition/issues/17#issuecomment-1067904258_

**Comment by infiniteblock** [comment]
These have worked in previous versions what is the issue...

**Comment by infiniteblock** [comment]
have tested both and working fine

**Comment by newfengye** [comment]
Sorry, I'm not careful enough. It's normal to test alone
