### ISSUE TITLE
Gravitational Anomaly

### ISSUE THREAD

**Issue by newfengye** [infiniteblock/MatterOverdrive-Community-Edition#2]
No Gravitational Anomaly
0.7.3

**Comment by infiniteblock** [comment]
Yes just rare unlike the over generation in previous versions

**Comment by infiniteblock** [comment]
you mite want to up the spawn rate in the config i will change it be default in 0.7.4

**Comment by newfengye** [comment]
Looking forward to the new version

**Comment by newfengye** [comment]
I've always wanted to play matter overdrive, but there are too many bugs
