### ISSUE TITLE
The android perk "Inertial Dampers" suggest you can buy a third tier "150%" fall damage reduction. 

### ISSUE THREAD

**Issue by Layarion** [infiniteblock/MatterOverdrive-Community-Edition#21]
The 50% and 100% fall damage reductions work as they should, but seems to have a minor cosmetic issue.  Showing a "150%" buy option after you get the second tier.

Before you buy the first tier, it says it will reduce fall damage by 50%. This is as it should be. You buy it, and the next tier says it will reduce fall damage by 100%. This is also as it should be. You buy it, but now for some reason it says 150% fall damage reduction instead of 100%.

It's not a big deal, and maybe it's a feature for some debuff that can remove some of your fall protection idk. But if that's not a feature, I think it hurts the perceived image of the mod to have small issues like this.

![image](https://user-images.githubusercontent.com/7917992/159601210-3526fe09-8d51-4c6b-b10e-ef27cdc31da0.png)

 - Forge Version: 14.23.5.2860
 - Minecraft Version: 1.12.2
 - MO Version: 0.7.7
 - Solo non-server world
 - Mods: On a curseforge app made modpack from scratch, no mods besides JEI and MO:CE installed in that modpack. All mods in the pack updated.

**Comment by infiniteblock** [comment]
Fixed in Dev
