### ISSUE TITLE
EnergyPack gets wasted if there is only one when gun consumes it.

### ISSUE THREAD

**Issue by Layarion** [infiniteblock/MatterOverdrive-Community-Edition#22]
If you only have one EnergyPack on you when your shotgun needs it, the shotgun consumes the EnergyPack but doesn't refill the ammo.

Seems to be 100% reproducible. Just have one pack in your hotbar, use the shotgun until it consumes the pack, and observe that the energy in the gun didn't increase when it consumed it.

It should have refilled the shotgun to full when it consumed the pack.

![javaw_QxYrtGRCbD](https://user-images.githubusercontent.com/7917992/159605362-cf938983-d087-4454-9e25-261ed72074ac.gif)

 - Forge Version: 14.23.5.2860
 - Minecraft Version: 1.12.2
 - MO Version: 0.7.7
 - Solo non-server world
 - Mods: On a curseforge app made modpack from scratch, no mods besides JEI and MO:CE installed in that modpack. All mods in the pack updated.

**Comment by infiniteblock** [comment]
Fixed in dev.
