### ISSUE TITLE
ItemMagnet perk rapidly drains batteries if there are many objects around.

### ISSUE THREAD

**Issue by Layarion** [infiniteblock/MatterOverdrive-Community-Edition#23]
When there is a large collection of objections around that can't be put in you for whatever reason (like when your inventory is full), the ItemMagnet perk will drain your battery alarmingly fast - especially if the Cyclic mod's "Experience Pylon" is nearby.

Fill your inventory up, and blow up a lot of blocks, or just break apart a couple of full chest. Turn the item magnet on, and watch your high capacity battery go bye bye really, really fast.

![javaw_Bc4oJBpLfm](https://user-images.githubusercontent.com/7917992/159606479-fc2f76a3-e1cc-494e-a5bd-f6d022180caa.gif)

If you have the mod "cyclic" installed, and have an "experience pylon" nearby, it will also drain it extremely fast.

![javaw_nC3NvHqLwf](https://user-images.githubusercontent.com/7917992/159608264-60873c7f-d996-4b65-aa68-4fff14de6aee.gif)

_I actually like the behavior in the first .gif, it reminds you of your batteries mortality._ It's a problem though when some popular mod in a popular pack kills your HighCapacityBattery in mere seconds. So I think it's working as it should when you don't factor in other mods and whatever weirdness they do, but maybe there's a way to make it work for the first .gif, but not for the second .gif? I think cyclic's "experience pylon" is somehow making the magnet think there is thousands of experience orbs in that block and it's trying to grab them. You have to set the pylon to "spray mode", and then turn "spray mode" off again before the bug is repeatable.

 - Forge Version: 14.23.5.2860
 - Minecraft Version: 1.12.2
 - MO Version: 0.7.7
 - Solo non-server world
 - Mods: On a curseforge app made modpack from scratch, no mods besides JEI and MO:CE installed in that modpack. All mods in the pack updated.

**Comment by infiniteblock** [comment]
the cyclic experience pylon is spraying out xp orbs and it uses 8 fe per item it picks up.
