### ISSUE TITLE
Feedback, I wish the guns could have the "looting" enchantment.

### ISSUE THREAD

**Issue by Layarion** [infiniteblock/MatterOverdrive-Community-Edition#25]
All the guns are unable to be enchanted with "Looting". So I have to find a different weapon if loot is my goal. Wish I could just enchant Looting onto them, or use some sort of upgrade module that has it.

**Comment by infiniteblock** [comment]
![image](https://user-images.githubusercontent.com/5800555/160261675-fb79267b-d92d-4fd7-aa48-1a2977c97d09.png)
Guns can be enchanted?

**Comment by Layarion** [comment]
ah my bad, i was trying the table
