### ISSUE TITLE
cloake Shield turns the screen completly white

### ISSUE THREAD

**Issue by Gandalf360one** [infiniteblock/MatterOverdrive-Community-Edition#3]
Forge Version: 14.23.5.2860
Matter Overdrive Version:  1.12.2-0.7.3
No optifine installed

When the player hold an item inside his hotbar while the cloak effect is active will get a complet white screen.
This can be prevented when the player hold an item with a durability bar in his off hand but this could maybe pls be fixed inside the mods code.

**Comment by infiniteblock** [comment]
Fixed in 0.7.4
