### ISSUE TITLE
Transporter bugs

### ISSUE THREAD

**Issue by Gandalf360one** [infiniteblock/MatterOverdrive-Community-Edition#5]
Forge Version: 14.23.5.2860
Matter Overdrive Version:  1.12.2-0.7.3

When holding more than one transporter together inside the hotbar and then placing one from the stacked ones at the ground the ones inside the hotbar will be configured and have a full fake energy buffer (0/0 RF).

The transporter wont show how much matter plasma is inside the internal tank (The one Probe/waila show there is some inside) till the transporter is set as sender or a anvailed destination is set. Reciver wont show that there is untill you set an invailed/availed destination.

**Comment by infiniteblock** [comment]
Fixed! in 0.7.4
