### ISSUE TITLE
Plasma Shotgun Power Shot

### ISSUE THREAD

**Issue by Gandalf360one** [infiniteblock/MatterOverdrive-Community-Edition#6]
Forge Version: 14.23.5.2860
Matter Overdrive Version:  1.12.2-0.7.3

When holding the plasma shotgun in the hand and holding down the right mouse key to charge it nothing will happen.

**Comment by infiniteblock** [comment]
i see that when u start a new world and use the plasma shotgun for the first time holding down the right mouse key makes a charging noise, but after a shot once it no longer works, even getting a new gun wont fix, reloading the world and grabbing a new gun seems to allow you another shot...

**Comment by infiniteblock** [comment]
Fixed in 0.7.4
