### ISSUE TITLE
Compatibility androids dont suffocate in Advanced Rockerty space

### ISSUE THREAD

**Issue by Njet75** [infiniteblock/MatterOverdrive-Community-Edition#7]
Tryed to add Androids dont suffocate in Advanced Rockerty config.
It wont work ,Am I doing something wrong?
![Skärmklipp](https://user-images.githubusercontent.com/8996171/148050937-1211b10f-0f9f-42c2-ab85-9d04bf3a601f.PNG)

**Comment by infiniteblock** [comment]
https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/1600

they have refused to add compatibility when all other space mods have, someone needs to bring up the new community edition.

**Comment by infiniteblock** [comment]
Have just talked to the dev's of advanced rocketry and they refuse to add any compatibility.
