### ISSUE TITLE
Are Androids supposed to need to eat?

### ISSUE THREAD

**Issue by Desempregago** [infiniteblock/MatterOverdrive-Community-Edition#8]

**Comment by Desempregago** [comment]
![image](https://user-images.githubusercontent.com/14002834/149212463-016a1c0c-81c1-4369-9397-039a364f41a6.png)

**Comment by infiniteblock** [comment]
You need to use a android station and install the "Zero Calories" 
![image](https://user-images.githubusercontent.com/5800555/150657941-d764e85b-fcf6-42f3-9ea1-1c45386de3a0.png)
